name: Build & Test

on: push

jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn build
      - run: yarn test